---
name: "Updatecli: Dependency Management"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: read

jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Apply
        run: "updatecli apply --config ./updatecli.d"
        env:
          UPDATECLI_GITHUB_ACTOR: CrystalMethod
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
